[package]
name = "kof"
version = "0.1.3"
license = "MIT"
repository = "https://github.com/pindjouf/kof.git"
description = "A Git-Based Note Management System"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
patharg = "0.4.0"
